import { definePack } from "./lib.js";

const CLOUD_CATEGORIES = [
  { id: "compute", name: "Compute" },
  { id: "storage", name: "Storage" },
  { id: "database", name: "Database" },
  { id: "networking", name: "Networking" },
  { id: "integration", name: "Integration" },
  { id: "analytics", name: "Analytics & ML" },
  { id: "security", name: "Security & Identity" },
  { id: "observability", name: "Observability & DevOps" },
];

export const awsPack = definePack({
  id: "aws",
  name: "Amazon Web Services",
  description: "Starter set of ~40 common AWS services",
  color: "#e8791b",
  categories: CLOUD_CATEGORIES,
  attributeSchema: {
    type: "object",
    additionalProperties: false,
    properties: {
      accountId: { type: "string", pattern: "^\\d{12}$", description: "12-digit AWS account id" },
      region: { type: "string", description: "e.g. eu-west-2" },
      arn: { type: "string" },
    },
  },
  stencils: [
    ["ec2", "EC2 Instance", "compute", "component", "EC2", ["AWS EC2"]],
    ["lambda", "Lambda Function", "compute", "component", "λ", ["AWS Lambda"]],
    ["ecs", "ECS Service", "compute", "component", "ECS", ["AWS ECS"]],
    ["eks", "EKS Cluster", "compute", "component", "EKS", ["AWS EKS", "Kubernetes"]],
    ["fargate", "Fargate Task", "compute", "component", "FRG", ["AWS Fargate"]],
    ["batch", "Batch Job", "compute", "component", "BAT", ["AWS Batch"]],
    ["s3", "S3 Bucket", "storage", "component", "S3", ["AWS S3"]],
    ["ebs", "EBS Volume", "storage", "component", "EBS", ["AWS EBS"]],
    ["efs", "EFS File System", "storage", "component", "EFS", ["AWS EFS"]],
    ["glacier", "S3 Glacier", "storage", "component", "GLA", ["AWS S3 Glacier"]],
    ["rds", "RDS Database", "database", "component", "RDS", ["AWS RDS"]],
    ["aurora", "Aurora Cluster", "database", "component", "AUR", ["AWS Aurora"]],
    ["dynamodb", "DynamoDB Table", "database", "component", "DDB", ["AWS DynamoDB"]],
    ["elasticache", "ElastiCache", "database", "component", "EC", ["AWS ElastiCache"]],
    ["redshift", "Redshift", "database", "component", "RS", ["AWS Redshift"]],
    ["neptune", "Neptune", "database", "component", "NEP", ["AWS Neptune"]],
    ["documentdb", "DocumentDB", "database", "component", "DOC", ["AWS DocumentDB"]],
    ["vpc", "VPC", "networking", "group", "VPC"],
    ["cloudfront", "CloudFront", "networking", "component", "CF", ["AWS CloudFront"]],
    ["route53", "Route 53", "networking", "component", "R53", ["AWS Route 53"]],
    ["api-gateway", "API Gateway", "networking", "component", "APIG", ["AWS API Gateway"]],
    ["elb", "Elastic Load Balancer", "networking", "component", "ELB", ["AWS ELB"]],
    ["sqs", "SQS Queue", "integration", "component", "SQS", ["AWS SQS"]],
    ["sns", "SNS Topic", "integration", "component", "SNS", ["AWS SNS"]],
    ["eventbridge", "EventBridge", "integration", "component", "EVB", ["AWS EventBridge"]],
    ["step-functions", "Step Functions", "integration", "component", "SFN", ["AWS Step Functions"]],
    ["mq", "Amazon MQ", "integration", "component", "MQ", ["Amazon MQ"]],
    ["kinesis", "Kinesis Stream", "analytics", "component", "KIN", ["AWS Kinesis"]],
    ["msk", "MSK (Kafka)", "analytics", "component", "MSK", ["AWS MSK", "Kafka"]],
    ["glue", "Glue Job", "analytics", "component", "GLU", ["AWS Glue"]],
    ["athena", "Athena", "analytics", "component", "ATH", ["AWS Athena"]],
    ["emr", "EMR Cluster", "analytics", "component", "EMR", ["AWS EMR"]],
    ["quicksight", "QuickSight", "analytics", "component", "QS", ["AWS QuickSight"]],
    ["sagemaker", "SageMaker", "analytics", "component", "SM", ["AWS SageMaker"]],
    ["bedrock", "Bedrock", "analytics", "component", "BR", ["AWS Bedrock"]],
    ["cognito", "Cognito", "security", "component", "COG", ["AWS Cognito"]],
    ["iam", "IAM", "security", "component", "IAM", ["AWS IAM"]],
    ["kms", "KMS", "security", "component", "KMS", ["AWS KMS"]],
    ["secrets-manager", "Secrets Manager", "security", "component", "SEC", ["AWS Secrets Manager"]],
    ["cloudwatch", "CloudWatch", "observability", "component", "CW", ["AWS CloudWatch"]],
    ["cloudtrail", "CloudTrail", "observability", "component", "CT", ["AWS CloudTrail"]],
    ["codepipeline", "CodePipeline", "observability", "component", "CP", ["AWS CodePipeline"]],
  ],
});

export const azurePack = definePack({
  id: "azure",
  name: "Microsoft Azure",
  description: "Starter set of ~40 common Azure services",
  color: "#2563eb",
  categories: CLOUD_CATEGORIES,
  attributeSchema: {
    type: "object",
    additionalProperties: false,
    properties: {
      subscriptionId: {
        type: "string",
        pattern: "^[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}$",
        description: "Azure subscription GUID",
      },
      resourceGroup: { type: "string" },
      region: { type: "string", description: "e.g. uksouth" },
    },
  },
  stencils: [
    ["vm", "Virtual Machine", "compute", "component", "VM", ["Azure VM"]],
    ["vmss", "VM Scale Set", "compute", "component", "VMSS", ["Azure VMSS"]],
    ["aks", "AKS Cluster", "compute", "component", "AKS", ["Azure AKS", "Kubernetes"]],
    ["container-apps", "Container Apps", "compute", "component", "CA", ["Azure Container Apps"]],
    ["functions", "Function App", "compute", "component", "FN", ["Azure Functions"]],
    ["app-service", "App Service", "compute", "component", "AS", ["Azure App Service"]],
    ["blob", "Blob Storage", "storage", "component", "BLOB", ["Azure Blob Storage"]],
    ["files", "Azure Files", "storage", "component", "FILE", ["Azure Files"]],
    ["disk", "Managed Disk", "storage", "component", "DISK", ["Azure Disk"]],
    ["data-lake", "Data Lake Gen2", "storage", "component", "ADLS", ["Azure Data Lake"]],
    ["sql", "SQL Database", "database", "component", "SQL", ["Azure SQL"]],
    ["cosmos", "Cosmos DB", "database", "component", "COS", ["Azure Cosmos DB"]],
    ["postgres", "PostgreSQL Flexible", "database", "component", "PG", ["Azure PostgreSQL"]],
    ["mysql", "MySQL Flexible", "database", "component", "MY", ["Azure MySQL"]],
    ["redis", "Cache for Redis", "database", "component", "RED", ["Azure Redis"]],
    ["synapse", "Synapse Analytics", "analytics", "component", "SYN", ["Azure Synapse"]],
    ["vnet", "Virtual Network", "networking", "group", "VNET"],
    ["front-door", "Front Door", "networking", "component", "AFD", ["Azure Front Door"]],
    ["cdn", "CDN", "networking", "component", "CDN", ["Azure CDN"]],
    ["dns", "DNS Zone", "networking", "component", "DNS", ["Azure DNS"]],
    ["app-gateway", "Application Gateway", "networking", "component", "AGW", ["Azure App Gateway"]],
    ["load-balancer", "Load Balancer", "networking", "component", "LB", ["Azure Load Balancer"]],
    ["expressroute", "ExpressRoute", "networking", "component", "ER", ["Azure ExpressRoute"]],
    ["service-bus", "Service Bus", "integration", "component", "SB", ["Azure Service Bus"]],
    ["event-grid", "Event Grid", "integration", "component", "EG", ["Azure Event Grid"]],
    ["event-hubs", "Event Hubs", "integration", "component", "EH", ["Azure Event Hubs"]],
    ["logic-apps", "Logic App", "integration", "component", "LA", ["Azure Logic Apps"]],
    ["apim", "API Management", "integration", "component", "APIM", ["Azure APIM"]],
    ["data-factory", "Data Factory", "analytics", "component", "ADF", ["Azure Data Factory"]],
    ["databricks", "Databricks", "analytics", "component", "DBX", ["Azure Databricks"]],
    ["stream-analytics", "Stream Analytics", "analytics", "component", "ASA", ["Azure Stream Analytics"]],
    ["ml", "Machine Learning", "analytics", "component", "AML", ["Azure ML"]],
    ["openai", "OpenAI Service", "analytics", "component", "AOAI", ["Azure OpenAI"]],
    ["entra", "Entra ID", "security", "component", "ID", ["Microsoft Entra ID"]],
    ["key-vault", "Key Vault", "security", "component", "KV", ["Azure Key Vault"]],
    ["monitor", "Monitor", "observability", "component", "MON", ["Azure Monitor"]],
    ["log-analytics", "Log Analytics", "observability", "component", "LOG", ["Azure Log Analytics"]],
    ["devops", "Azure DevOps", "observability", "component", "ADO", ["Azure DevOps"]],
    ["acr", "Container Registry", "observability", "component", "ACR", ["Azure ACR"]],
  ],
});

export const gcpPack = definePack({
  id: "gcp",
  name: "Google Cloud Platform",
  description: "Starter set of ~40 common GCP services",
  color: "#059669",
  categories: CLOUD_CATEGORIES,
  attributeSchema: {
    type: "object",
    additionalProperties: false,
    properties: {
      projectId: { type: "string", pattern: "^[a-z][a-z0-9-]{4,28}[a-z0-9]$" },
      region: { type: "string", description: "e.g. europe-west2" },
    },
  },
  stencils: [
    ["compute-engine", "Compute Engine", "compute", "component", "GCE", ["GCP Compute Engine"]],
    ["gke", "GKE Cluster", "compute", "component", "GKE", ["GCP GKE", "Kubernetes"]],
    ["cloud-run", "Cloud Run", "compute", "component", "RUN", ["GCP Cloud Run"]],
    ["cloud-functions", "Cloud Functions", "compute", "component", "CFN", ["GCP Cloud Functions"]],
    ["app-engine", "App Engine", "compute", "component", "GAE", ["GCP App Engine"]],
    ["gcs", "Cloud Storage", "storage", "component", "GCS", ["GCP Cloud Storage"]],
    ["persistent-disk", "Persistent Disk", "storage", "component", "PD", ["GCP Persistent Disk"]],
    ["filestore", "Filestore", "storage", "component", "FST", ["GCP Filestore"]],
    ["cloud-sql", "Cloud SQL", "database", "component", "CSQL", ["GCP Cloud SQL"]],
    ["spanner", "Spanner", "database", "component", "SPN", ["GCP Spanner"]],
    ["bigtable", "Bigtable", "database", "component", "BT", ["GCP Bigtable"]],
    ["firestore", "Firestore", "database", "component", "FS", ["GCP Firestore"]],
    ["memorystore", "Memorystore", "database", "component", "MEM", ["GCP Memorystore"]],
    ["bigquery", "BigQuery", "analytics", "component", "BQ", ["GCP BigQuery"]],
    ["vpc", "VPC Network", "networking", "group", "VPC"],
    ["cloud-cdn", "Cloud CDN", "networking", "component", "CDN", ["GCP Cloud CDN"]],
    ["cloud-dns", "Cloud DNS", "networking", "component", "DNS", ["GCP Cloud DNS"]],
    ["cloud-lb", "Cloud Load Balancing", "networking", "component", "GLB", ["GCP Load Balancing"]],
    ["interconnect", "Cloud Interconnect", "networking", "component", "IC", ["GCP Interconnect"]],
    ["pubsub", "Pub/Sub", "integration", "component", "PS", ["GCP Pub/Sub"]],
    ["cloud-tasks", "Cloud Tasks", "integration", "component", "TSK", ["GCP Cloud Tasks"]],
    ["cloud-scheduler", "Cloud Scheduler", "integration", "component", "SCH", ["GCP Cloud Scheduler"]],
    ["workflows", "Workflows", "integration", "component", "WF", ["GCP Workflows"]],
    ["eventarc", "Eventarc", "integration", "component", "EVT", ["GCP Eventarc"]],
    ["apigee", "Apigee", "integration", "component", "APG", ["GCP Apigee"]],
    ["dataflow", "Dataflow", "analytics", "component", "DF", ["GCP Dataflow"]],
    ["dataproc", "Dataproc", "analytics", "component", "DP", ["GCP Dataproc"]],
    ["data-fusion", "Data Fusion", "analytics", "component", "FUS", ["GCP Data Fusion"]],
    ["looker", "Looker", "analytics", "component", "LKR", ["Looker"]],
    ["vertex-ai", "Vertex AI", "analytics", "component", "VAI", ["GCP Vertex AI"]],
    ["iam", "Cloud IAM", "security", "component", "IAM", ["GCP IAM"]],
    ["kms", "Cloud KMS", "security", "component", "KMS", ["GCP KMS"]],
    ["secret-manager", "Secret Manager", "security", "component", "SEC", ["GCP Secret Manager"]],
    ["cloud-armor", "Cloud Armor", "security", "component", "ARM", ["GCP Cloud Armor"]],
    ["cloud-logging", "Cloud Logging", "observability", "component", "LOG", ["GCP Cloud Logging"]],
    ["cloud-monitoring", "Cloud Monitoring", "observability", "component", "MON", ["GCP Cloud Monitoring"]],
    ["cloud-trace", "Cloud Trace", "observability", "component", "TRC", ["GCP Cloud Trace"]],
    ["cloud-build", "Cloud Build", "observability", "component", "CB", ["GCP Cloud Build"]],
    ["artifact-registry", "Artifact Registry", "observability", "component", "AR", ["GCP Artifact Registry"]],
  ],
});
